server:
  port: 9905

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9922/eureka/

spring:
  application:
    name: server-service
  cloud:
    loadbalancer:
      retry:
        enabled: false

