
server:
  port: 9903

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9922/eureka/

spring:
  application:
    name: zuul-service
  cloud:
    loadbalancer:
      retry:
        enabled: false

zuul:
  routes:
    server:
      path: /server/**
      serviceId: server-service
      sensitiveHeaders: "*"
    web:
      path: /web/**
      serviceId: web-service
      senditiveHeaders: "*"



